site_name: MDavies 2324 Portfolio
site_description: 'Martin Davies 2023 2024 portfolio'
site_author: 'Martin Davies'
docs_dir: docs/
repo_name: 'MrDaviesKellett/Portfolio'
repo_url: 'https://github.com/MrDaviesKellett/Portfolio'
nav:
    - Home: index.md
theme:
  name: 'readthedocs'