# This is a basic workflow to help you get started with Actions

name: mkdocs deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MKDOCS_ADMIN_PASSWORD: ${{ secrets.MKDOCS_ADMIN_PASSWORD }}
  MKDOCS_STAFF_PASSWORD: ${{ secrets.MKDOCS_STAFF_PASSWORD }}
  MKDOCS_STUDENT_PASSWORD: ${{ secrets.MKDOCS_STUDENT_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildmarp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure buildmarp dir exists
        run: mkdir -p buildmarp

      - name: Copy images directory (if exists)
        run: if [[ -d docs/Slides/img ]]; then cp -R img buildmarp/img; fi

      - name: Check if docs/Slides folder exists
        id: docs-folder-exists
        run: bash -c "[[ -d docs/Slides/ ]] ; echo \"has_docs=\$?\" >> \"$GITHUB_OUTPUT\""

      - name: Marp Build (docs/Slides folder, if exists)
        if: steps.docs-folder-exists.outputs.has_docs == '0'
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: -I docs/Slides/ -o buildmarp/docs/
        env:
          MARP_USER: root:root

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./buildmarp/
          clean-exclude: pr-preview/
          
  buildmkdocs:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
          
      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Install pillow cairosvg
        run: pip install pillow cairosvg

      - name: Install mkdocs encryption
        run: pip install mkdocs-encryptcontent-plugin
        
      - name: Deploy mkdocs
        run: mkdocs gh-deploy --force
