# This is a basic workflow to help you get started with Actions

name: mkdocs deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MKDOCS_ADMIN_PASSWORD: ${{ secrets.MKDOCS_ADMIN_PASSWORD }}
  MKDOCS_STAFF_PASSWORD: ${{ secrets.MKDOCS_STAFF_PASSWORD }}
  MKDOCS_STUDENT_PASSWORD: ${{ secrets.MKDOCS_STUDENT_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
          
      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Install pillow cairosvg
        run: pip install pillow cairosvg

      - name: Install mkdocs encryption
        run: pip install mkdocs-encryptcontent-plugin
        
      - name: deploy mkdocs
      - run: mkdocs gh-deploy --force
